### PR TITLE
1.12.0.0 personal

### PR DESCRIPTION
**Pull request by zer0Kerbal**
# Version 1.12.0.0 - >>-- personal recompile by @zer0Kerbal --<<
- personal compile for KSP 1.12.1
- modernize folder structure
- backend automation
- added Version.tt

### CODE REVIEW

**Comment by Garryck** [comment]
Is there any way I can download this?

**Comment by zer0Kerbal** [comment]
@Garryck I can provide the .dll 'as-is' - it is working for me on all versions of KSP up to 1.12.1.
or I could push the changes and you could recompile?

**Comment by Garryck** [comment]
A .dll would be the simplest, I think. I'm not even set up to compile anything at the moment.

**Comment by zer0Kerbal** [comment]
~~**I will push a zip in the near future - probably this weekend (if not sooner).** 🔜 [Done.]()~~

_May I adopt this mod with your blessing? That way can do a full release to curseforge, spacedock, github, and CKAN_ ❓ 
If so - would you: 🍎 
1. post on the [forums](https://forum.kerbalspaceprogram.com/index.php?/topic/137197-*) granting me permission? 
2. add me to the authors on [curseforge](https://www.curseforge.com/kerbal/ksp-mods/ksp-chroma-control/settings/members) 
3. :D

**Comment by Garryck** [comment]
Thanks! (I assume the rest of the comment was aimed at Chris Guckes?)

**Pull request closed without merging**
